spring:

  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    hikari:
      connection-test-query: SELECT 1

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    ###
    #Activate it to run the test cases
    ###
    #defer-datasource-initialization: true

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

  sql:
    init:
      platform: postgres

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





