spring:

  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none

    database: POSTGRESQL
    ###
    #Activate it to run the test cases
    ###
    #defer-datasource-initialization: true

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

  sql:
    init:
      platform: postgres

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





