spring:

 datasource:
  url: jdbc:h2:mem:bookdb
  username: sa
  password: password
  hikari:
   connection-test-query: SELECT 1

 jpa:
  database: H2
  show_sql: true
  generate-ddl: true
  hibernate:
   ddl-auto: validate

 sql:
  init:
   platform: h2

 flyway:
  baseline-on-migrate: true
  validate-on-migrate: true


