spring:

 datasource:
  url: jdbc:h2:mem:bookdb
  username: sa
  password: password

  hikari:
   connection-test-query: SELECT 1
   driver-class-name: org.h2.Driver

 jpa:
  show_sql: true
  generate-ddl: true
  database-platform: org.hibernate.dialect.H2Dialect

  hibernate:
   ddl-auto: validate
  database: h2

 sql:
  init:
   platform: h2


 flyway:
  baseline-on-migrate: true
  validate-on-migrate: true


